### ISSUE TITLE
Must have GIFs!!!!!!!!

### ISSUE THREAD

**Issue by mikefortun** [PECE-project/drupal-pece#127]
It seems that GIFs do not GIF in the platform. I tried uploading them as an image artifact, and just pasting it into text boxes somewhere, and there is still no giffing going on...

**Comment by revagomes** [comment]
The following Drupal module should help fixing that issue: 

**Animated gif support for image styles**
https://www.drupal.org/project/animgif_support

**Comment by mikefortun** [comment]
Yes please!

**Comment by revagomes** [comment]
Fixed on [PECE v1.24](https://github.com/PECE-project/pece-distro/releases/tag/v1.24).
