### ISSUE TITLE
permissions on centerforethnography fked up

### ISSUE THREAD

**Issue by mikefortun** [PECE-project/drupal-pece#131]
on slack too: 
permissions are misbehaving on centerforethnography.org. I have checked carefully against other sites but on this one, when an open artifact is assigned to a private group and group visibility is set to private (restricted) I can still see the artifact even when I am not signed in at all.  Kim has students tryong to work on the site who are VERY concerned about privacy so this needs to be fixed ASAP but I don't know what the problem is.  When I sign in as Big Admin the only difference I can see ( aside from CfE not yet being on SSL but I didn't think that would matter) is on the PHP and web server settings.  For all the other sites these are
PHP	7.0.33-0ubuntu0.16.04.7 and
Web server	Apache/2.4.18 (Ubuntu)
but for centerforethnography.org they are
PHP	7.2.24-0ubuntu0.18.04.1 and
Web server	Apache/2.4.29 (Ubuntu)
but I am a idiot but not so idiot as to PUSH THAT REBUILD PERMISSIONS BUTTON like the bad part of me wanted to..

**Comment by edmargomes** [comment]
Fix in this PR https://github.com/PECE-project/drupal-pece/pull/139 with automated tests.

**Comment by revagomes** [comment]
PECE v1.23 fixes permission conflicts that was the root cause of this issue.
