### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by sebas5384** [PECE-project/drupal-pece#2]
Some related resources about the issue:
- http://blog.ploeh.dk/2015/01/15/10-tips-for-better-pull-requests/
- https://www.drupal.org/node/1326662

Always write expected result as acceptance criteria.

**Comment by unixjazz** [comment]
Closing this issue: the "contributors' guide" has been written and included in the official PECE 1.0 documentation (which will be merged with 'master' soon). [Here is the preview](http://pece.readthedocs.org/en/latest/contributors.html), feel free to add to it!
