### ISSUE TITLE
php-mcrypt no longer part of PHP 7.3+

### ISSUE THREAD

**Issue by ibara** [PECE-project/drupal-pece#211]
As the title says.
Users can still install through pecl, but it's more work.
I can update docs if needed, but how much does this affect us? (Will new-PECE use php-mcrypt?)

**Comment by revagomes** [comment]
We will have to update the documentation. 
PECE depends on mcrypt for the two-factor authentication functionality.

**Comment by revagomes** [comment]
@ibara I will review TFA issue queue to check if there is an alternative to Mcrypt already in use.

**Comment by ibara** [comment]
Thanks!

**Comment by revagomes** [comment]
@ibara, 
the TFA module requires either the PHP OpenSSL or Mcrypt extensions to be installed on the web server.  The mcrypt is only used as 'preferred' for decryption if it is installed.
