### ISSUE TITLE
The PHP YAML parser is no longer shipped with Ubuntu.

### ISSUE THREAD

**Issue by ibara** [PECE-project/drupal-pece#26]
Just an FYI for people, PECE uses a yaml parser to do some work.
Historically, Ubuntu used to ship the parser with the default PHP installation so we never had to worry about it. However, the newer Ubuntus do not. Worse, they don't even offer it as a package.

One can (and this is what we do) manually build and install the yaml parser. But it has me worried that since Ubuntu has dropped official support perhaps we need to either:
a) Fork the YAML parser and have it live in a separate repo (PECE-project/yaml-parser, for example) for easy installation (not super ideal but definitely manageable and communicable to new instance installers)
b) Use a different YAML parser?
c) Something else?

**Comment by revagomes** [comment]
@ibara, 

[Spyc](https://github.com/mustangostang/spyc) library has being already used on early releases of PECE Distro to cover  similar issues on other OS.

PECE v1.21 has also added YAML parser module to provide a standard API. 

See https://www.drupal.org/project/yaml_parser for more information.
