### ISSUE TITLE
Annotations migration

### ISSUE THREAD

**Issue by MegaKeegMan** [PECE-project/drupal-pece#347]
- There was mention of migrating annotation content into https://www.drupal.org/project/entity_notes
- Though it will still be worth considering keeping the annotation content type or utilizing comments, which are fieldable

**Comment by judsonmb** [comment]
?

Em qui., 5 de out. de 2023 18:55, Keegan Rankin ***@***.***>
escreveu:

**Comment by mikefortun** [comment]
i think this is going to be one of the harder decisions to make. but it did take a quick look at the open issues and bugs for notes and — keeping in mind that i am complete amateur- it was not very reassuring and some seemed to be open for a long time. i can’t tell the level of support but it seems low. someone who knows what they’re doing should take a closer look.

**Comment by mlncn** [comment]
This is continued in #455
