### ISSUE TITLE
Migrate artifacts to media types referenced by a single artifact content type

### ISSUE THREAD

**Issue by mlncn** [PECE-project/drupal-pece#368]
If the metadata that is specific to an artifact lives in the referenced media type (length of video and audio artifacts being the main example) that is fine.  (Ideally length would be automatically calculated and saved, if possible.)

It is important that this be able to be produced as an API exposing Dublin Core items.

Related to #335

**Comment by mlncn** [comment]
Currently i'm leaning toward keeping artifacts in separate content types as Renato suggested.

The main reason not to, so far, is honestly only faceted search, and we can provide a "Select all" feature for artifacts so it's easy to filter to all artifacts, similar to if artifact were one content type.

But a lot more to look into here before making the decision.

**Comment by mikefortun** [comment]
I would lean towards keeping too but, in the way I always feel the need to end my comments, what do I know?

if no strong reasoning emerges for going one way or the other, then maybe the decision is about which is easier/cheaper for migration purposes

**Comment by MegaKeegMan** [comment]
In this issue just above, I mention using access by ref for managing permissions. That is not directly related to this issue, but one effect of using the above module for managing permissions would be extra configuration per node bundle per field per access category. That is 4 configurations per artifact type, which adds up to around 40, plus the 2 needed on the group content type. This number could be kept well under 10 if we reduce the artifact to a single content type. Not necessarily the decider, but worth a mention here.

**Comment by MegaKeegMan** [comment]
On the other hand, configuring conditional fields could also represent a significant enough amount of work, including some unknowns. I will take a look at how much variation there is between fields, and whether any field dependencies might become burdensome.

**Comment by MegaKeegMan** [comment]
After a quick analysis, the sentiment is still the same—it would be awesome to have faceted search, which condensing into one type would enable, but for just about everything else, it will be better to leave the content types as they are. So maybe let's just leave it as is.

**Comment by judsonmb** [comment]
Ok ok ok

Em qui., 14 de dez. de 2023 20:37, Keegan Rankin ***@***.***>
escreveu:
