### ISSUE TITLE
Implement faceted search

### ISSUE THREAD

**Issue by wolcen** [PECE-project/drupal-pece#400]
* Use Drupal db search backend, filtering for content and taxonomy (group terms) by tag
* Filter by:
  * content type
  * contributor

**Comment by wolcen** [comment]
Related to #389

**Comment by mikefortun** [comment]
contributor

**Comment by wolcen** [comment]
![image](https://github.com/PECE-project/drupal-pece/assets/7354450/7bdba495-6063-4c1a-b661-ba224fa6452b)

**Comment by MegaKeegMan** [comment]
Any pages that list content will be an implementation of the search view
