### ISSUE TITLE
Associate icons with various content types (and group terms)

### ISSUE THREAD

**Issue by MegaKeegMan** [PECE-project/drupal-pece#481]
On version 1 of PECE, many content types had a unique icon associated with them. These icons came from the font-awesome library. Here is the list (bundle - icon id):
* audio artifact - music
* video artifact - video
* website artifact - link
* image artifact -  (replace with thumbnail of image)
* pdf artifact - file-pdf
* tabular artifact - table
* bundle - boxes-stacked
* text artifact - file-lines
* group - users
* memo - lightbulb
* photo essay - images (replace with thumbnail if available)
* pece essay - icons (replace with thumbnail if available)
* timeline essay - timeline (replace with thumbnail if available)
* project - newspaper (replace with thumbnail if available)
* analytic - question
* annotation - file-circle-question
* substantive logic - puzzle-piece (replace with thumbnail)
* user - user (replace with profile photo)

**Comment by MegaKeegMan** [comment]
Here is an example of how to load type tray icons...
1. with a preprocess hook,  get the icon from the node type settings and add the icon url to the render array:
```
<?php

use Drupal\node\Entity\NodeType;

/**
 * Implements hook_preprocess_node().
 */
function pece_example_preprocess_node(array &$variables) {
  $node = $variables['node'];

  if ($node->getEntityTypeId() === 'node') {
    $content_type = $node->getType();

    $content_type_config = NodeType::load($content_type);
    if (isset($content_type_config)) {
      $third_party_property = $content_type_config->get('third_party_settings');
      if (!empty($third_party_property['type_tray']['type_icon'])) {
        $variables['content_type_icon'] = $third_party_property['type_tray']['type_icon'];
      }
    }
  }
}

```
2. Then render the icon in the template
this is what it looks like if it is always an SVG
```
<div class="type-tray__icon type-tray__icon--vector">
  {% if content_type_icon %}
     {{ source(content_type_icon) }}
  {% endif %}
</div>

```
Here is what the relevant markup looks like in the type tray module (allowing for more than just SVGs):
```
<div class="type-tray__icon {% if icon_filetype == 'svg' %}type-tray__icon--vector{% else %}type-tray__icon--raster{% endif %}">
  {% if icon_url %}
    {% if icon_filetype == 'svg' %}
     {{ source(icon_url) }}
    {% else %}
    <img width="100" height="100" alt="{{ icon_alt }}" src="{{ icon_url }}" />
    {% endif %}
  {% endif %}
</div>
```

**Comment by MegaKeegMan** [comment]
This won't work for Groups or Users, since type tray is not available for non-node entities yet. See https://www.drupal.org/project/type_tray/issues/3438075

**Comment by multilectical** [comment]
@MegaKeegMan this could work for this: https://www.drupal.org/project/paragraphs_browser

**Comment by mlncn** [comment]
The "Icon from Type Tray" field is available to be placed for all content types (nodes).

Groups, which should use a different image per group if available, will instead be configured with an image field and a fallback image.
