### ISSUE TITLE
Content Permissions Overriding Group Permissions

### ISSUE THREAD

**Issue by lindsaypoirier** [PECE-project/drupal-pece#58]
This artifact: https://theasthmafiles.org/content/interview-rachel-greenberg-transcript

has been set to Open and is in a public group and a private group. 

The private group ([Philadelphia Civic Field School](https://theasthmafiles.org/content/philadelphia-civic-field-school)) has been set to Use Default Roles and Permissions for Roles and Permissions, and the artifact itself has been set to Use Group Defaults for content visibility. 

<img width="794" alt="Screen Shot 2019-07-12 at 11 59 45 AM" src="https://user-images.githubusercontent.com/2657884/61152195-98632a80-a49c-11e9-8c18-3d846d8dac7a.png">

Currently, the group is completely Open. 

The group permission settings should override the content permission settings, and with multiple groups, should adopt the most restrictive group permissions settings, so this artifact should be visible only to group members (of all groups).

**Comment by revagomes** [comment]
Here goes Organic Groups module documentation page for later reference in regards to Content Visibility: [Access Control - Content Visibility](https://www.drupal.org/node/2014755)

**Comment by revagomes** [comment]
PECE v1.19 has a update that adds a new field on Group content type to set group content visibility also a warning message is set letting users aware that content visibility might change when assigning it to an open group.
